# -*- coding: utf-8 -*-
"""Código-calculadora de piscina-10-11-25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-VAMGnUe91TP8otv70r3IbgplMzCqfC

# Após muitos aprendizados e estudos e revisões e alterações e melhorias chegamos nesse código final !
"""

import math
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from typing import Dict, Tuple


# =======================
# FUNÇÕES DE CÁLCULO DE MATERIAIS
# =======================

def calcular_area(largura: float, comprimento: float) -> float:
    return largura * comprimento


def calcular_perimetro(largura: float, comprimento: float) -> float:
    return 2 * (largura + comprimento)


def calcular_blocos(area: float) -> float:
    return area * 12.5


def calcular_tela(perimetro: float, profundidade: float) -> float:
    return (perimetro + 4 * profundidade) / 5


def calcular_impermeabilizante1(area: float) -> int:
    return math.ceil(area / 9)


def calcular_impermeabilizante2(area: float) -> int:
    return math.ceil(area / 4)


def calcular_cimento(area: float) -> float:
    return (0.013 + 0.038 + 0.14) * area / 50


def calcular_areia(area: float) -> float:
    return (0.065 + 0.004 + 0.025) * area


def calcular_ligmassa(area: float) -> float:
    return (0.0026 + 0.05) * area


def calcular_revestimento(area: float) -> float:
    return area


def calcular_argamassa(area: float) -> float:
    return 0.45 * area


def calcular_rejunte(area: float) -> float:
    return 0.05 * area / 20


def calcular_espacadores(area: float) -> float:
    return 12 * area


# =======================
# ENTRADA DE DADOS
# =======================

def coletar_dados_projeto() -> Dict[str, float]:
    print("\n=== PROJETO PARA UMA FAMÍLIA ===")
    dados = {}
    dados["Nome_projeto"] = input("Nome do projeto ou cliente: ").strip()
    dados["Num_pessoas_familia"] = int(input("Quantas pessoas compõem a família? "))
    dados["Vai_hidromassagem"] = input("O projeto inclui hidromassagem? (Sim/Não): ").strip().capitalize()

    tipo = input("Tipo de piscina (Azulejo/Vinilico): ").strip().lower()
    dados["Tipo_piscina"] = "Vinilico" if tipo.startswith("v") else "Azulejo"

    print("\n=== DADOS DA PISCINA ===")
    dados["Largura"] = float(input("Largura da piscina (m): ").replace(',', '.'))
    dados["Comprimento"] = float(input("Comprimento da piscina (m): ").replace(',', '.'))

    fundo_declive = input("Piscina com fundo em declive? (Sim/Não): ").strip().capitalize()
    if fundo_declive == "Sim":
        dados["Profundidade_min"] = float(input("Profundidade mínima (m): ").replace(',', '.'))
        dados["Profundidade_max"] = float(input("Profundidade máxima (m): ").replace(',', '.'))
    else:
        dados["Profundidade_min"] = dados["Profundidade_max"] = float(input("Profundidade (m): ").replace(',', '.'))

    dados["Usar_revestimento"] = input("Tipo de acabamento (Revestimento/Outro): ").strip().capitalize()
    if dados["Usar_revestimento"] == "Revestimento":
        dados["Revestimento_largura_peca"] = float(input("Largura da peça (m): ").replace(',', '.'))
        dados["Revestimento_altura_peca"] = float(input("Altura da peça (m): ").replace(',', '.'))

    return dados


# =======================
# CÁLCULOS PRINCIPAIS
# =======================

def calcular_tudo(
    dados_piscina: Dict[str, float],
    custo_unitario: Dict[str, float],
    extras: Dict[str, float],
    preco_agua_por_litro: float = 0.01,
    caminhos_enchimento: int = 3,
    fluxo_mangueira_lph: float = 1000.0
) -> Tuple[Dict[str, float], Dict[str, float], Dict[str, float], float]:

    largura = dados_piscina["Largura"]
    comprimento = dados_piscina["Comprimento"]
    profundidade = (dados_piscina["Profundidade_min"] + dados_piscina["Profundidade_max"]) / 2

    area = calcular_area(largura, comprimento)
    perimetro = calcular_perimetro(largura, comprimento)

    materiais = {
        "Blocos": calcular_blocos(area),
        "Tela para Quina Vivas (caixas)": calcular_tela(perimetro, profundidade),
        "Impermeabilizante1 (caixas 20kg)": calcular_impermeabilizante1(area),
        "Impermeabilizante2 (caixas 20kg)": calcular_impermeabilizante2(area),
        "Cimento (sacos)": calcular_cimento(area),
        "Areia (m³)": calcular_areia(area),
        "Ligmassa (litros)": calcular_ligmassa(area),
        "Argamassa ACIII (kg)": calcular_argamassa(area),
        "Rejunte Acrílico (sacos)": calcular_rejunte(area),
        "Espaçadores (unidades)": calcular_espacadores(area)
    }

    if dados_piscina["Usar_revestimento"] == "Revestimento":
        materiais["Revestimento (m²)"] = calcular_revestimento(area)

    if dados_piscina["Vai_hidromassagem"] == "Sim":
        materiais["Hidromassagem (kit)"] = 1

    if dados_piscina["Tipo_piscina"] == "Vinilico":
        area_manta = (area + perimetro * profundidade) * 1.10
        materiais["Manta Vinilica (m²)"] = round(area_manta, 3)

    # Enchimento da piscina
    volume_m3 = largura * comprimento * profundidade
    litros = volume_m3 * 1000
    materiais["Volume de água (L)"] = round(litros, 2)
    materiais["Caminhões de enchimento (unidades)"] = caminhos_enchimento
    tempo_horas = litros / (caminhos_enchimento * fluxo_mangueira_lph)
    materiais["Tempo estimado enchimento (h)"] = round(tempo_horas, 2)

    custos = {m: materiais[m] * custo_unitario.get(m, 0) for m in materiais}
    custos["Custo de enchimento (R$)"] = round(litros * preco_agua_por_litro, 2)

    if "Hidromassagem (kit)" in materiais:
        custos["Hidromassagem (kit)"] = extras.get("custo_hidromassagem_kit", 0)

    fases = {
        "Alvenaria": ["Blocos", "Cimento (sacos)"],
        "Impermeabilização": ["Impermeabilizante1 (caixas 20kg)", "Impermeabilizante2 (caixas 20kg)"],
        "Chapisco/Reboco": ["Cimento (sacos)", "Areia (m³)", "Argamassa ACIII (kg)"],
        "Revestimento": ["Revestimento (m²)", "Argamassa ACIII (kg)"],
        "Acabamento": ["Rejunte Acrílico (sacos)", "Espaçadores (unidades)"],
        "Enchimento": ["Custo de enchimento (R$)"]
    }
    if "Hidromassagem (kit)" in materiais:
        fases["Extras"] = ["Hidromassagem (kit)"]

    custos_fase = {fase: sum(custos.get(m, 0) for m in mats) for fase, mats in fases.items()}
    return materiais, custos, custos_fase, area


# =======================
# GRÁFICOS
# =======================

def gerar_graficos(materiais, custos, custos_fase, area):
    import seaborn as sns
    import numpy as np
    os.makedirs("graficos", exist_ok=True)

    # Paleta pastel suave
    cores = sns.color_palette("pastel")

    if area == 0:
        quant_por_m2 = {m: 0 for m in materiais}
    else:
        quant_por_m2 = {m: q / area for m, q in materiais.items()}

    # === NOVO: Gráfico em LINHAS com escala logarítmica ===
    plt.figure(figsize=(10, 6))
    x = np.arange(len(quant_por_m2))
    y = list(quant_por_m2.values())
    labels = list(quant_por_m2.keys())

    plt.plot(x, y, color="#9BBFE0", linewidth=2.5, marker="o", markersize=6,
             markerfacecolor="#F6BD60", alpha=0.8)

    plt.yscale("log")  # Escala logarítmica pra mostrar todos os valores
    plt.xticks(x, labels, rotation=80, ha="right")
    plt.grid(True, which="both", linestyle="--", alpha=0.4)
    plt.title("Quantidade de Materiais por m²", fontsize=13, fontweight="bold")
    plt.ylabel("Quantidade (escala logarítmica)")
    plt.tight_layout()
    plt.savefig("graficos/quantidade_por_m2.png", dpi=200)
    plt.close()

    # === Custos por fase ===
    plt.figure(figsize=(10,6))
    plt.barh(list(custos_fase.keys()), list(custos_fase.values()), color=cores[1])
    plt.xlabel("Custo (R$)")
    plt.title("Distribuição de custos por fase", fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.savefig("graficos/custos_por_fase.png", dpi=200)
    plt.close()

    # === Custos por material ===
    plt.figure(figsize=(12,6))
    sorted_custos = dict(sorted(custos.items(), key=lambda x: x[1], reverse=True))
    plt.barh(list(sorted_custos.keys()), list(sorted_custos.values()), color=cores[2])
    plt.xlabel("Custo (R$)")
    plt.title("Custos por material (inclui enchimento da piscina)", fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.savefig("graficos/custos_por_material.png", dpi=200)
    plt.close()

    # === Enchimento da Piscina (mantém o que já estava lindo) ===
    if "Custo de enchimento (R$)" in custos:
        fig, ax = plt.subplots(figsize=(9, 5))
        parametros = ["Volume (L)", "Caminhões", "Tempo (h)", "Custo (R$)"]
        valores = [
            materiais.get("Volume de água (L)", 0),
            materiais.get("Caminhos de enchimento (unidades)", 0),
            materiais.get("Tempo estimado enchimento (h)", 0),
            custos.get("Custo de enchimento (R$)", 0)
        ]
        bar_colors = ["#A8DADC", "#F6BD60", "#BDB2FF", "#FFADAD"]
        barras = ax.bar(parametros, valores, color=bar_colors, alpha=0.8, edgecolor="gray")
        ax.set_title("Enchimento da Piscina - Volume, Caminhões, Tempo e Custo", fontsize=14, fontweight="bold")
        ax.set_ylabel("Valores de enchimento", fontsize=11)
        ax.grid(axis="y", linestyle="--", alpha=0.5)
        for i, b in enumerate(barras):
            altura = b.get_height()
            ax.text(b.get_x() + b.get_width()/2, altura + (altura*0.02 if altura>0 else 0.1),
                    f"{valores[i]:,.2f}", ha="center", va="bottom", fontsize=10, color="#333")
        plt.tight_layout()
        plt.savefig("graficos/custo_enchimento.png", dpi=200)
        plt.close(fig)


# =======================
# RELATÓRIOS
# =======================

def salvar_excel(dados_piscina, materiais, custos, custos_fase):
    with pd.ExcelWriter("relatorio_piscina.xlsx") as writer:
        pd.DataFrame([dados_piscina]).to_excel(writer, sheet_name="Dados_Projeto", index=False)
        pd.DataFrame(list(materiais.items()), columns=["Material", "Quantidade"]).to_excel(writer, sheet_name="Materiais", index=False)
        pd.DataFrame(list(custos.items()), columns=["Material", "Custo (R$)"]).to_excel(writer, sheet_name="Custos", index=False)
        pd.DataFrame(list(custos_fase.items()), columns=["Fase", "Custo (R$)"]).to_excel(writer, sheet_name="Custos_Fase", index=False)
    print("✅ Planilha Excel gerada: relatorio_piscina.xlsx")


def gerar_pdf(dados_piscina, materiais, custos, custos_fase):
    doc = SimpleDocTemplate("orcamento_piscina.pdf", pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    styles.add(ParagraphStyle(name='TitleStyle', fontSize=16, alignment=1, spaceAfter=12))
    story.append(Paragraph(f"Orçamento de Piscina - {dados_piscina['Nome_projeto']}", styles['TitleStyle']))

    def add_section(title: str, data: Dict[str, float]):
        story.append(Spacer(1, 8))
        story.append(Paragraph(f"<b>{title}</b>", styles['Heading3']))
        for k, v in data.items():
            story.append(Paragraph(f"{k}: {v}", styles['Normal']))

    add_section("Dados do Projeto", dados_piscina)
    add_section("Materiais", materiais)
    add_section("Custos por Material (R$)", {k: f"{v:.2f}" for k, v in custos.items()})
    add_section("Custos por Fase (R$)", {k: f"{v:.2f}" for k, v in custos_fase.items()})

    if "Volume de água (L)" in materiais:
        enchimento_data = {
            "Volume de água (L)": materiais.get("Volume de água (L)", 0),
            "Caminhos de enchimento (unidades)": materiais.get("Caminhos de enchimento (unidades)", 0),
            "Tempo estimado enchimento (h)": materiais.get("Tempo estimado enchimento (h)", 0),
            "Custo de enchimento (R$)": custos.get("Custo de enchimento (R$)", 0)
        }
        add_section("Informações de Enchimento", enchimento_data)


    # Adiciona gráficos
    for img_name in sorted(os.listdir("graficos")):
        img_path = os.path.join("graficos", img_name)
        if os.path.exists(img_path):
            story.append(Spacer(1, 12))
            story.append(Image(img_path, width=6*inch, height=4*inch))

    story.append(Spacer(1, 12))
    story.append(Paragraph("✅ Relatório gerado automaticamente com gráficos em tons pastéis para melhor visualização.", styles['Normal']))

    doc.build(story)
    print("✅ PDF gerado: orcamento_piscina.pdf")


# =======================
# EXECUÇÃO PRINCIPAL
# =======================

def main():
    custo_unitario = {
        "Blocos": 1.5,
        "Tela para Quina Vivas (caixas)": 50,
        "Impermeabilizante1 (caixas 20kg)": 100,
        "Impermeabilizante2 (caixas 20kg)": 150,
        "Cimento (sacos)": 25,
        "Areia (m³)": 150,
        "Ligmassa (litros)": 10,
        "Revestimento (m²)": 60,
        "Argamassa ACIII (kg)": 20,
        "Rejunte Acrílico (sacos)": 40,
        "Espaçadores (unidades)": 0.1
    }
    extras = {"custo_hidromassagem_kit": 5000}

    preco_agua_por_litro = 0.01
    caminhos_enchimento = 3
    fluxo_mangueira_lph = 1000.0

    dados_piscina = coletar_dados_projeto()
    materiais, custos, custos_fase, area = calcular_tudo(
        dados_piscina, custo_unitario, extras,
        preco_agua_por_litro, caminhos_enchimento, fluxo_mangueira_lph
    )

    gerar_graficos(materiais, custos, custos_fase, area)
    salvar_excel(dados_piscina, materiais, custos, custos_fase)
    gerar_pdf(dados_piscina, materiais, custos, custos_fase)


if __name__ == "__main__":
    main()

!pip install reportlab

from graphviz import Digraph

# === CONFIGURAÇÃO GERAL ===
flux = Digraph("Fluxograma_Piscina", format="png")
flux.attr(rankdir="LR")  # horizontal
flux.attr(size="15,9")   # tamanho grande
flux.attr(dpi="300")     # alta resolução
flux.attr("node", fontname="Arial", fontsize="20", style="filled", fillcolor="#E6F0FF", color="#444")

# === 1️⃣ ENTRADA DE DADOS ===
flux.node("A", "Início", shape="oval", fillcolor="#B3C7F9")
flux.node("B", "Entrada de dados do projeto\n(Nome, Nº pessoas, Hidromassagem,\nDimensões, Tipo de revestimento)", shape="parallelogram", fillcolor="#D6E4FF")
flux.node("C", "Fundo em declive?", shape="diamond", fillcolor="#FFF9C4")
flux.node("D", "Ler profundidade mínima e máxima", shape="rectangle", fillcolor="#E8F5E9")
flux.node("E", "Usar profundidade única\n(sem declive)", shape="rectangle", fillcolor="#E8F5E9")

# === 2️⃣ TIPO DE PISCINA ===
flux.node("F", "Tipo de piscina?", shape="diamond", fillcolor="#FFF9C4")
flux.node("G", "Vinílica\n→ Calcular manta com desperdício\n→ Corrigir sobreposição base/parede\n→ Calcular perímetro", shape="rectangle", fillcolor="#E8F5E9")
flux.node("H", "Azulejo\n→ Calcular revestimento e argamassa", shape="rectangle", fillcolor="#E8F5E9")

# === 3️⃣ CÁLCULOS DE VOLUME E CUSTOS ===
flux.node("I", "Calcular volume em litros\n(enchimento total)", shape="rectangle", fillcolor="#E8F5E9")
flux.node("J", "Calcular custo da água (R$)\ncom base no volume", shape="rectangle", fillcolor="#E8F5E9")
flux.node("K", "Calcular tempo estimado de enchimento\n(caminhos de água)", shape="rectangle", fillcolor="#E8F5E9")

# === 4️⃣ RELATÓRIOS E GRÁFICOS ===
flux.node("L", "Gerar gráficos horizontais\n(quantidade por m², custos, fases)", shape="rectangle", fillcolor="#DDEEFF")
flux.node("M", "Gerar relatórios:\n→ Excel\n→ PDF completo", shape="rectangle", fillcolor="#DDEEFF")
flux.node("N", "Fim", shape="oval", fillcolor="#B3C7F9")

# === CONEXÕES ===
flux.edge("A", "B")
flux.edge("B", "C")
flux.edge("C", "D", label="Sim")
flux.edge("C", "E", label="Não")
flux.edge("D", "F")
flux.edge("E", "F")
flux.edge("F", "G", label="Vinílico")
flux.edge("F", "H", label="Azulejo")
flux.edge("G", "I")
flux.edge("H", "I")
flux.edge("I", "J")
flux.edge("J", "K")
flux.edge("K", "L")
flux.edge("L", "M")
flux.edge("M", "N")

# === AJUSTE DE ESPAÇAMENTO ===
flux.attr(ranksep="1.5", nodesep="1.2")  # mais espaço entre blocos

# === EXPORTAÇÃO ===
output_path = flux.render("fluxograma_calculadora_piscina_HD", cleanup=True)
print(f"✅ Fluxograma HD gerado com sucesso: {output_path}")

"""# Por fim pedi ao chat auxilio para deixar profissional além de funcional, aprimorar a leitura, organizzar os itens e dar aquela enxugada em repetições, assim ele fez:"""

import math
import os
from dataclasses import dataclass, asdict
from typing import Dict, Tuple

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch


# =========================
# 🎯 ESTRUTURA DE DADOS
# =========================
@dataclass
class ProjetoPiscina:
    nome: str
    pessoas: int
    hidromassagem: bool
    tipo: str
    largura: float
    comprimento: float
    profundidade_min: float
    profundidade_max: float
    revestimento: bool = False
    revest_largura: float = 0.0
    revest_altura: float = 0.0


# =========================
# ⚙️ FUNÇÕES DE CÁLCULO
# =========================
def calcular_area(l, c): return l * c
def calcular_perimetro(l, c): return 2 * (l + c)
def calcular_volume(l, c, p): return l * c * p * 1000  # em litros


def calcular_materiais(p: ProjetoPiscina) -> Dict[str, float]:
    """Calcula todos os materiais necessários a partir dos dados do projeto."""
    area = calcular_area(p.largura, p.comprimento)
    perimetro = calcular_perimetro(p.largura, p.comprimento)
    profundidade = (p.profundidade_min + p.profundidade_max) / 2

    materiais = {
        "Blocos": area * 12.5,
        "Tela para Quina Vivas (caixas)": (perimetro + 4 * profundidade) / 5,
        "Impermeabilizante1 (caixas 20kg)": math.ceil(area / 9),
        "Impermeabilizante2 (caixas 20kg)": math.ceil(area / 4),
        "Cimento (sacos)": (0.013 + 0.038 + 0.14) * area / 50,
        "Areia (m³)": (0.065 + 0.004 + 0.025) * area,
        "Ligmassa (litros)": (0.0026 + 0.05) * area,
        "Argamassa ACIII (kg)": 0.45 * area,
        "Rejunte Acrílico (sacos)": 0.05 * area / 20,
        "Espaçadores (unidades)": 12 * area,
    }

    if p.revestimento:
        materiais["Revestimento (m²)"] = area
    if p.hidromassagem:
        materiais["Hidromassagem (kit)"] = 1
    if p.tipo.lower().startswith("v"):
        materiais["Manta Vinilica (m²)"] = round((area + perimetro * profundidade) * 1.1, 3)

    volume = calcular_volume(p.largura, p.comprimento, profundidade)
    materiais.update({
        "Volume de água (L)": volume,
        "Caminhões de enchimento (unidades)": 3,
        "Tempo estimado enchimento (h)": round(volume / (3 * 1000.0), 2)
    })
    return materiais


def calcular_custos(materiais: Dict[str, float], custo_unit: Dict[str, float],
                    extras: Dict[str, float], preco_agua_l: float) -> Tuple[Dict[str, float], Dict[str, float]]:
    custos = {m: q * custo_unit.get(m, 0) for m, q in materiais.items()}
    custos["Custo de enchimento (R$)"] = materiais["Volume de água (L)"] * preco_agua_l
    if "Hidromassagem (kit)" in materiais:
        custos["Hidromassagem (kit)"] = extras.get("custo_hidromassagem_kit", 0)

    fases = {
        "Alvenaria": ["Blocos", "Cimento (sacos)"],
        "Impermeabilização": ["Impermeabilizante1 (caixas 20kg)", "Impermeabilizante2 (caixas 20kg)"],
        "Chapisco/Reboco": ["Cimento (sacos)", "Areia (m³)", "Argamassa ACIII (kg)"],
        "Revestimento": ["Revestimento (m²)", "Argamassa ACIII (kg)"],
        "Acabamento": ["Rejunte Acrílico (sacos)", "Espaçadores (unidades)"],
        "Enchimento": ["Custo de enchimento (R$)"],
    }
    if "Hidromassagem (kit)" in materiais:
        fases["Extras"] = ["Hidromassagem (kit)"]

    custos_fase = {fase: sum(custos.get(m, 0) for m in mats) for fase, mats in fases.items()}
    return custos, custos_fase


# =========================
# 📊 GRÁFICOS
# =========================
def gerar_graficos(materiais, custos, custos_fase, area):
    os.makedirs("graficos", exist_ok=True)
    sns.set(style="whitegrid", palette="pastel")

    # Quantidade por m²
    plt.figure(figsize=(10, 6))
    q_m2 = {m: q / area if area else 0 for m, q in materiais.items()}
    plt.plot(q_m2.keys(), q_m2.values(), marker="o")
    plt.yscale("log")
    plt.xticks(rotation=80)
    plt.title("Quantidade de Materiais por m² (escala log)")
    plt.tight_layout()
    plt.savefig("graficos/quantidade_por_m2.png", dpi=200)
    plt.close()

    # Custos por fase
    plt.figure(figsize=(8, 5))
    plt.barh(list(custos_fase.keys()), list(custos_fase.values()))
    plt.title("Distribuição de custos por fase")
    plt.tight_layout()
    plt.savefig("graficos/custos_por_fase.png", dpi=200)
    plt.close()

    # Custos por material
    plt.figure(figsize=(10, 6))
    plt.barh(*zip(*sorted(custos.items(), key=lambda x: x[1], reverse=True)))
    plt.title("Custos por material")
    plt.tight_layout()
    plt.savefig("graficos/custos_por_material.png", dpi=200)
    plt.close()


# =========================
# 📁 RELATÓRIOS
# =========================
def salvar_excel(projeto: ProjetoPiscina, materiais, custos, custos_fase):
    with pd.ExcelWriter("relatorio_piscina.xlsx") as writer:
        pd.DataFrame([asdict(projeto)]).to_excel(writer, sheet_name="Dados_Projeto", index=False)
        pd.DataFrame(materiais.items(), columns=["Material", "Quantidade"]).to_excel(writer, sheet_name="Materiais", index=False)
        pd.DataFrame(custos.items(), columns=["Material", "Custo (R$)"]).to_excel(writer, sheet_name="Custos", index=False)
        pd.DataFrame(custos_fase.items(), columns=["Fase", "Custo (R$)"]).to_excel(writer, sheet_name="Custos_Fase", index=False)
    print("✅ Planilha Excel gerada: relatorio_piscina.xlsx")


def gerar_pdf(projeto: ProjetoPiscina, materiais, custos, custos_fase):
    doc = SimpleDocTemplate("orcamento_piscina.pdf", pagesize=letter)
    styles = getSampleStyleSheet()
    story = [Paragraph(f"Orçamento de Piscina - {projeto.nome}",
                       ParagraphStyle('Title', fontSize=16, alignment=1))]

    def secao(titulo, dados):
        story.append(Spacer(1, 8))
        story.append(Paragraph(f"<b>{titulo}</b>", styles['Heading3']))
        for k, v in dados.items():
            story.append(Paragraph(f"{k}: {v}", styles['Normal']))

    secao("Dados do Projeto", asdict(projeto))
    secao("Materiais", materiais)
    secao("Custos", {k: f"{v:.2f}" for k, v in custos.items()})
    secao("Custos por Fase", {k: f"{v:.2f}" for k, v in custos_fase.items()})

    for img in sorted(os.listdir("graficos")):
        story.append(Spacer(1, 10))
        story.append(Image(os.path.join("graficos", img), width=6 * inch, height=4 * inch))

    story.append(Spacer(1, 12))
    story.append(Paragraph("✅ Relatório gerado automaticamente com gráficos em tons pastéis.", styles['Normal']))
    doc.build(story)
    print("✅ PDF gerado: orcamento_piscina.pdf")


# =========================
# 🚀 EXECUÇÃO
# =========================
def main():
    custo_unitario = {
        "Blocos": 1.5, "Tela para Quina Vivas (caixas)": 50,
        "Impermeabilizante1 (caixas 20kg)": 100, "Impermeabilizante2 (caixas 20kg)": 150,
        "Cimento (sacos)": 25, "Areia (m³)": 150, "Ligmassa (litros)": 10,
        "Revestimento (m²)": 60, "Argamassa ACIII (kg)": 20,
        "Rejunte Acrílico (sacos)": 40, "Espaçadores (unidades)": 0.1
    }
    extras = {"custo_hidromassagem_kit": 5000}

    p = ProjetoPiscina(
        nome=input("Nome do projeto: "),
        pessoas=int(input("Número de pessoas: ")),
        hidromassagem=input("Inclui hidromassagem? (s/n): ").lower() == "s",
        tipo=input("Tipo de piscina (Azulejo/Vinílico): ").capitalize(),
        largura=float(input("Largura (m): ")),
        comprimento=float(input("Comprimento (m): ")),
        profundidade_min=float(input("Profundidade mínima (m): ")),
        profundidade_max=float(input("Profundidade máxima (m): ")),
        revestimento=input("Usará revestimento? (s/n): ").lower() == "s"
    )

    materiais = calcular_materiais(p)
    custos, custos_fase = calcular_custos(materiais, custo_unitario, extras, preco_agua_l=0.01)
    area = calcular_area(p.largura, p.comprimento)

    gerar_graficos(materiais, custos, custos_fase, area)
    salvar_excel(p, materiais, custos, custos_fase)
    gerar_pdf(p, materiais, custos, custos_fase)


if __name__ == "__main__":
    main()

!pip install reportlab